facebook:
    base_url: https://graph.facebook.com
    class: oauth2
    login_url: https://www.facebook.com/dialog/oauth
    scope: email
    paths:
        access_token:
            path: /oauth/access_token
            arguments: [client_id, client_secret, code, grant_type, redirect_uri]
            requires_authentication: false
        search:
            path: /search
            arguments: [q, type]
            response: {root: 'data'}
        current_user:
            path: /me
            defaults: {fields: "id,name,email,username,picture"}
            arguments: []
            response: {map: {picture: picture.data}}
        posts:
            path: /{id}/posts
            arguments: [id, limit]
            defaults: {count: 50, return_ssl_resources: 1}
            response: {root: 'data', map: {text: message, created_at: created_time, mentions: message_tags}}
            url_has_params: true
        get_by_id:
            path: /{id}
            arguments: [id]
            url_has_params: true
        get_by_username:
            path: /{username}
            arguments: [username]
            url_has_params: true


twitter:
    base_url: https://api.twitter.com
    class: oauth1
    login_url: https://api.twitter.com/oauth/authenticate
    scope: ~
    paths:
        search:
            path: /1.1/users/search.json
            arguments: [q]
            response: {map: {username: screen_name}}
        access_token:
            path: /oauth/access_token
            arguments: [oauth_verifier]
        request_token:
            path: /oauth/request_token
            arguments: [oauth_callback]
        current_user:
            path: /1.1/account/verify_credentials.json
            arguments: []
            response: {map: {username: screen_name}}
        posts:
            path: /1.1/statuses/user_timeline.json
            arguments: [user_id, count]
            defaults: {count: 50, trim_user: true, include_rts: false}
            response: {map: {id: id_str, urls: entities.urls, mentions: entities.user_mentions }}
            url_has_params: true
        get_by_id:
            path: /1.1/users/show.json
            arguments: [user_id]
            defaults: {include_entities: 'false'}
            response: { map: {username: screen_name}}
        get_by_username:
            path: /1.1/users/show.json
            arguments: [screen_name]
            defaults: {include_entities: 'false'}
            response: { map: {username: screen_name}}

google:
    base_url: ~
    class: oauth2
    login_url: https://accounts.google.com/o/oauth2/auth
    scope: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    paths:
        access_token:
            path: https://accounts.google.com/o/oauth2/token
            arguments: [client_id, client_secret, code, grant_type, redirect_uri]
            requires_authentication: false
            method: POST
        current_user:
            path: https://www.googleapis.com/oauth2/v1/userinfo
            arguments: []
            response: {map: {username: email}}
google_simple:
    class: simple
    base_url: ~
    paths:
        place_search:
            path: https://maps.googleapis.com/maps/api/place/nearbysearch/json
            arguments: [keyword, location, radius]
            defaults: {sensor: 'false'}
            response: {root: 'results'}
        freebase_reconcile:
            path: https://www.googleapis.com/freebase/v1/reconcile
            arguments: [name, kind, prop, limit, confidence]
        freebase_search:
            path: https://www.googleapis.com/freebase/v1/search
            arguments: [query, filter, limit]
            response: {root: 'result'}
        freebase_topic:
            path: https://www.googleapis.com/freebase/v1/topic/{mid}
            url_has_params: true
            arguments: [mid]

github:
    class: oauth2
    base_url: https://api.github.com
    paths:
        repo:
            path: /repos/{owner}/{repo}
            url_has_params: true
            arguments: [owner, repo]
            requires_authentication: false
        issues:
            path: /repos/{owner}/{repo}/issues
            url_has_params: true
            arguments: [owner, repo, state, sort, labels]
            requires_authentication: false
